name: Evohome Helper (edge)
version: dev-e94f07c
description: This service adds presence detection and other cost saving measures to any Honeywell Evohome installation
url: https://github.com/lexbrugman/evohome-helper
image: 'ghcr.io/lexbrugman/evohome-helper-edge-{arch}'
slug: evohome_helper_edge
init: false
homeassistant_api: true
options:
  evohome:
    username:
    password:
    location_name:
    off_temp_threshold: 15.0
  presence:
    entities: []
    last_home_grace_time: 86400
    heating_schedule_grace_time: 1800
  auto_eco:
    enabled: true
    weather_entity:
    outside_temp_threshold: 18.0
    inside_temp_diff: 1.0
schema:
  evohome:
    username: email
    password: password
    location_name: str
    off_temp_threshold: float
  presence:
    entities:
      - str
    last_home_grace_time: int
    heating_schedule_grace_time: int
  auto_eco:
    enabled: bool
    weather_entity: str?
    outside_temp_threshold: float
    inside_temp_diff: float
arch:
  - aarch64
  - amd64
