name: Builder
run-name: Builder (${{ inputs.app }})

on:
  workflow_dispatch:
    inputs:
      app:
        description: app slug
        required: true
        type: string
      version:
        description: app version
        required: true
        type: string
      artifact_url:
        description: app artifact url
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ inputs.app }} app
    outputs:
      archs: ${{ steps.architecture_data.outputs.archs }}
      image: ${{ steps.info.outputs.image }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6.0.2

      - name: Set version
        run: |
          yq e '.version = "${{ inputs.version }}"' -i ./${{ inputs.app }}/config.yaml

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ inputs.app }}"

      - name: Unpack artifact
        run: |
          cd ./${{ inputs.app }}
          wget -O artifact.tar.gz ${{ inputs.artifact_url }}
          tar -zxvf artifact.tar.gz --strip-components=1 -C rootfs

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construct architecture data
        id: architecture_data
        run: |
          echo 'archs=${{ steps.info.outputs.architectures }}' >> "$GITHUB_OUTPUT"
          echo 'arch_flags=--${{ join(fromJSON(steps.info.outputs.architectures), ' --') }}' >> "$GITHUB_OUTPUT"

      - name: Build ${{ inputs.app }} app
        uses: home-assistant/builder@2025.11.0
        with:
          args: |
            ${{ steps.architecture_data.outputs.arch_flags }} \
            --target /data/${{ inputs.app }} \
            --image "$(echo ${{ steps.info.outputs.image }} | cut -d'/' -f3)" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon

      - name: Commit version
        run: |
          git config --global user.name "Home Assistant app builder"
          git add ./${{ inputs.app }}/config.yaml
          if git commit -m "New ${{ inputs.app }} build (${{ inputs.version }})"; then
            git pull --rebase
            git push
          fi

  cleanup:
    runs-on: ubuntu-latest
    name: Cleanup ${{ inputs.app }} app packages for ${{ matrix.arch }}
    needs: build
    strategy:
      matrix:
        arch: ${{ fromJSON(needs.build.outputs.archs) }}
    permissions:
      packages: write

    steps:
      - name: Construct package data
        id: package_data
        run: |
          echo "package_name=$(echo ${{ needs.build.outputs.image }} | cut -d'/' -f3 | sed 's/{arch}/${{ matrix.arch }}/g')" >> "$GITHUB_OUTPUT"

      - name: Cleanup untagged packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ steps.package_data.outputs.package_name }}
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: true

      - name: Cleanup old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ steps.package_data.outputs.package_name }}
          package-type: container
          min-versions-to-keep: 6
          ignore-versions: ${{ inputs.version }}
